/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProductCatgoriesRouteImport } from './routes/ProductCatgories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductNameRouteImport } from './routes/product.$name'
import { Route as CollectionIdRouteImport } from './routes/collection/$id'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCatgoriesRoute = ProductCatgoriesRouteImport.update({
  id: '/ProductCatgories',
  path: '/ProductCatgories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductNameRoute = ProductNameRouteImport.update({
  id: '/product/$name',
  path: '/product/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ProductCatgories': typeof ProductCatgoriesRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/wishlist': typeof WishlistRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/collection/$id': typeof CollectionIdRoute
  '/product/$name': typeof ProductNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ProductCatgories': typeof ProductCatgoriesRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/wishlist': typeof WishlistRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/collection/$id': typeof CollectionIdRoute
  '/product/$name': typeof ProductNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ProductCatgories': typeof ProductCatgoriesRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/wishlist': typeof WishlistRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/collection/$id': typeof CollectionIdRoute
  '/product/$name': typeof ProductNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ProductCatgories'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/orders'
    | '/register'
    | '/wishlist'
    | '/categories/$category'
    | '/collection/$id'
    | '/product/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ProductCatgories'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/orders'
    | '/register'
    | '/wishlist'
    | '/categories/$category'
    | '/collection/$id'
    | '/product/$name'
  id:
    | '__root__'
    | '/'
    | '/ProductCatgories'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/orders'
    | '/register'
    | '/wishlist'
    | '/categories/$category'
    | '/collection/$id'
    | '/product/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductCatgoriesRoute: typeof ProductCatgoriesRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  WishlistRoute: typeof WishlistRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  CollectionIdRoute: typeof CollectionIdRoute
  ProductNameRoute: typeof ProductNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ProductCatgories': {
      id: '/ProductCatgories'
      path: '/ProductCatgories'
      fullPath: '/ProductCatgories'
      preLoaderRoute: typeof ProductCatgoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$name': {
      id: '/product/$name'
      path: '/product/$name'
      fullPath: '/product/$name'
      preLoaderRoute: typeof ProductNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$id': {
      id: '/collection/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductCatgoriesRoute: ProductCatgoriesRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  WishlistRoute: WishlistRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  CollectionIdRoute: CollectionIdRoute,
  ProductNameRoute: ProductNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
